# This is just an example! Please see available options to customize Navidrome for your needs at
# https://www.navidrome.org/docs/usage/configuration-options/#available-options

LogLevel = 'WARN'
ScanSchedule = '@every 24h'
TranscodingCacheSize = '150MiB'
MusicFolder = '/Users/sparkes/Music/Media.localized/'
DataFolder = '/Users/sparkes/Music/navidrome'

# This is the default path for Homebrew installed ffmpeg
FFmpegPath = '/opt/homebrew/bin/ffmpeg'

PID.Track = "albumid,discnumber,tracknumber,title"
PID.Album = "albumartistid,album,albumversion"
